# -- SuperSponge configuration --
# All super sponge configuration settings can be edited here.
super-sponge:
  properties:
    # Should lava be cleared by the super sponge?
    clear-lava: true
    # Should water be cleared by the super sponge?
    clear-water: true
    # Should super sponge absorb water/lava in a sphere shape?
    # If this is false, the super sponge will absorb a cube based on radius.
    absorb-sphere: false
    # Should super sponges update surrounding blocks when placed
    # If this is enabled, water/lava will re-fill
    block-updates: false
    # Delay between placing super sponges. Set to -1 to disable.
    placement-delay: 5
    # Delay between breaking super sponges. Set to -1 to disable.
    break-delay: 5
    # Radius for which this sponge should clear.
    clear-radius: 8
  # Item configuration for the super sponge.
  item:
    name: "&c&lSuper Sponge"
    lore:
      - "&7Soaks up water and lava in a 16 block radius."
    enchant-glow: true