name: SuperSponge
version: ${project.version}
main: me.modify.supersponge.SuperSponge
description: Sponge enhancing plugin which adds a new super sponge item to the game.
api-version: 1.18
softdepend: [CoreProtect]